---
galaxy_info:
  author:
    - Ben Visser (@noqcks)
    - Aaron Pederson (@aaronpederson)
  company: "TELUS digital"
  description: "AWS CodeDeploy agent installation"
  license: MIT
  version: 1.0.0
  platforms:
    - name: debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
    - name: EL
      versions:
        - 7
  categories:
    - networking
    - system
